import {NextRequest,NextResponse} from 'next/server';import JSZip from 'jszip';import {LEO_TEMPLATES} from '@/data/website-templates';export const runtime='nodejs';
export async function POST(req:NextRequest){
 const b=await req.json();const t=LEO_TEMPLATES.find(x=>x.id===String(b.template_id));if(!t)return NextResponse.json({error:'Template not found.'},{status:404});
 const zip=new JSZip();const pkg={name:t.id,private:true,scripts:{dev:'next dev',build:'next build',start:'next start'},dependencies:{next:'16.3.6',react:'19.1.0','react-dom':'19.1.0'}};
 zip.file('package.json',JSON.stringify(pkg,null,2));
 zip.file('app/layout.tsx',`import './globals.css'; export const metadata={title:'${t.name}',description:'Free website template'}; export default function Layout({children}:{children:React.ReactNode}){return <html lang="en"><body>{children}</body></html>}`);
 zip.file('app/globals.css',`*{box-sizing:border-box}body{margin:0;background:#09090b;color:#fff;font-family:Arial,sans-serif}a{color:inherit;text-decoration:none}.wrap{max-width:1100px;margin:auto;padding:24px}.nav{display:flex;justify-content:space-between;gap:20px;align-items:center}.links{display:flex;gap:18px}.hero{padding:90px 0;display:grid;gap:20px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{padding:24px;border:1px solid #27272a;border-radius:20px;background:#111113}@media(max-width:700px){.grid{grid-template-columns:1fr}.links{gap:10px;font-size:14px}.hero{padding:55px 0}}`);
 zip.file('app/page.tsx',`import Link from 'next/link'; export default function Home(){return <main className="wrap"><nav className="nav"><b>${t.name}</b><div className="links"><Link href="/">Home</Link><Link href="/contact">Contact</Link></div></nav><section className="hero"><p>${t.type.toUpperCase()}</p><h1>${t.name}</h1><p>${t.description}</p><div><Link href="/contact">Get started →</Link></div></section><section className="grid"><div className="card"><h2>What we offer</h2><p>Replace this with the client's real services, products or programs.</p></div><div className="card"><h2>Why choose us</h2><p>Add real proof, credentials and testimonials supplied by the client.</p></div><div className="card"><h2>Take the next step</h2><p>Use the contact page for the real email, WhatsApp or booking link.</p></div></section></main>}`);
 zip.file('app/contact/page.tsx',`import Link from 'next/link'; export default function Contact(){return <main className="wrap"><nav className="nav"><b>${t.name}</b><Link href="/">← Home</Link></nav><section className="hero"><h1>Contact</h1><p>Replace this copy with the client's real contact details.</p><a href="mailto:YOUR_EMAIL@example.com">YOUR_EMAIL@example.com</a><a href="https://wa.me/YOUR_NUMBER">WhatsApp</a></section></main>}`);
 zip.file('README.md',`# ${t.name}\n\nFree LEO OS template source.\nType: ${t.type}\nPages: ${t.pages.join(', ')}\n\nThis is a simple 2-page starter. Replace all marked contact/content placeholders with real client information before publishing. Free templates do not require a hosting subscription.`); 
 const archive=await zip.generateAsync({type:'uint8array'});
 const body=new ArrayBuffer(archive.byteLength);
 new Uint8Array(body).set(archive);
 return new NextResponse(body,{headers:{'Content-Type':'application/zip','Content-Disposition':`attachment; filename="${t.id}-free-template.zip"`}});
}
