'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { siteData } from '@/data/site';
const appPrefixes = ['/dashboard','/app','/projects','/agents','/deployments','/analytics','/api-keys','/audit','/auth','/account','/admin','/developers','/docs','/integrations','/leo-ai','/notifications','/observability','/organizations','/resources','/setup','/support','/status','/team','/templates','/tutorials','/webhooks','/whats-new'];
export function Footer(){
  const pathname=usePathname();
  if (appPrefixes.some(prefix => pathname === prefix || pathname.startsWith(`${prefix}/`))) return null;
  return <footer className="site-footer border-t border-zinc-900 py-12"><div className="mx-auto grid max-w-7xl gap-8 px-4 md:grid-cols-4"><div><div className="text-xl font-black tracking-tight">LEONARDX</div><p className="mt-3 text-sm text-zinc-400">{siteData.tagline}</p></div><div><h3 className="font-bold">Explore</h3><div className="mt-3 grid gap-2 text-sm text-zinc-400"><Link href="/about">About</Link><Link href="/portfolio">Portfolio</Link><Link href="/pricing">Pricing</Link><Link href="/resources">Resources</Link><Link href="/docs">Documentation</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/refund-policy">Refund Policy</Link></div></div><div><h3 className="font-bold">Support</h3><div className="mt-3 grid gap-2 text-sm text-zinc-400"><Link href="/contact">Contact</Link><Link href="/support">Help center</Link><Link href="/status">System status</Link><a href={`mailto:${siteData.email}`}>{siteData.email}</a></div></div><div><h3 className="font-bold">Platform</h3><div className="mt-3 grid gap-2 text-sm text-zinc-400"><Link href="/app">Leo workspace</Link><Link href="/projects">Projects</Link><Link href="/integrations">Integrations</Link><Link href="/developers">Developer platform</Link></div></div></div><div className="mx-auto mt-8 max-w-7xl px-4 text-xs text-zinc-600">© 2026 LeonardX. Built with Next.js.</div></footer>
}
