"use client";
import { useEffect, useRef, useState } from "react";
import { Bot, Mic, Send, Trash2, Image as ImageIcon, Sparkles, Lightbulb, Rocket, Wrench, Code2, X, Maximize2, Volume2 } from "lucide-react";
import { createBrowserClient } from "@supabase/ssr";

type Msg={role:"user"|"assistant";content:string;image?:string};
type VoiceMode = "text" | "input" | "chat";
const actions=[
 {label:"Let’s brainstorm",prompt:"Let's brainstorm ideas with me",icon:Lightbulb},
 {label:"Let’s create",prompt:"Let's create something together",icon:Sparkles},
 {label:"Let’s deploy",prompt:"Let's deploy a website",icon:Rocket},
 {label:"Let’s fix",prompt:"Let's fix my code",icon:Wrench},
 {label:"Let’s code",prompt:"Let's code something",icon:Code2},
];
function getBrowserSupabase(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;return url&&key?createBrowserClient(url,key):null}
export function LEOWidget({full=false}:{full?:boolean}){
 const [open,setOpen]=useState(full);const [messages,setMessages]=useState<Msg[]>([]);const [input,setInput]=useState("");const [loading,setLoading]=useState(false);const [recording,setRecording]=useState(false);const [voiceMode,setVoiceMode]=useState<VoiceMode>("text");const [voiceStatus,setVoiceStatus]=useState("Ready");const [welcomeName,setWelcomeName]=useState("there");const [plan,setPlan]=useState<string|null>(null);const media=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);const sidRef=useRef("");const recognitionRef=useRef<any>(null);
 useEffect(()=>{const sid=localStorage.getItem("leo_chat_id")||crypto.randomUUID();sidRef.current=sid;localStorage.setItem("leo_chat_id",sid);const s=getBrowserSupabase();const load=async()=>{try{const session=s?(await s.auth.getSession()).data.session:null;const response=await fetch(`/api/chat?session_id=${sid}`,{headers:session?{Authorization:`Bearer ${session.access_token}`}:{}});const d={messages:[],...await response.json()} as {messages?:Msg[];profile?:{full_name?:string};plan?:string};setMessages(d.messages||[]);setPlan(d.plan||null);const n=d.profile?.full_name?.trim();if(n)setWelcomeName(n.split(/\s+/)[0]);}catch{}};void load()},[]);
 async function token(){const s=getBrowserSupabase();return s?(await s.auth.getSession()).data.session?.access_token||"":""}
 async function speakReply(text:string){if(typeof window==="undefined"||!("speechSynthesis" in window)) return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.rate=1;utterance.pitch=1;utterance.volume=1;window.speechSynthesis.speak(utterance)}
 async function send(text=input){if(!text.trim()||loading)return;const nextText=text.trim();setInput("");setMessages(m=>[...m,{role:"user",content:nextText}]);setLoading(true);try{const t=await token();const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{})},body:JSON.stringify({session_id:sidRef.current,message:nextText})});const d=await r.json();const reply=d.reply||d.error||"Leo could not complete that request.";setMessages(m=>[...m,{role:"assistant",content:reply}]);if(voiceMode ==="chat") await speakReply(reply)}catch{const reply="Leo is temporarily unavailable.";setMessages(m=>[...m,{role:"assistant",content:reply}]);if(voiceMode ==="chat") await speakReply(reply)}finally{setLoading(false)}}
 async function generateImage(){const prompt=input||"A modern business website hero image";setLoading(true);try{const t=await token();const r=await fetch("/api/generate-image",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({prompt})});const d=await r.json();setMessages(m=>[...m,{role:"assistant",content:d.error||`Image generated. ${d.credits_remaining??""} credits left.`,image:d.url}])}finally{setLoading(false)}}
 function stopRecording(){if(media.current&&media.current.state!=="inactive") media.current.stop();setRecording(false);setVoiceStatus("Ready")}
 function startVoiceInput(){if(recording){stopRecording();return}navigator.mediaDevices.getUserMedia({audio:true}).then(stream=>{const rec=new MediaRecorder(stream);chunks.current=[];rec.ondataavailable=e=>chunks.current.push(e.data);rec.onstop=async()=>{const blob=new Blob(chunks.current,{type:"audio/webm"});const fd=new FormData();fd.append("audio",blob,"voice.webm");const response=await fetch("/api/voice",{method:"POST",body:fd});const text=decodeURIComponent(response.headers.get("X-Transcript")||"");stream.getTracks().forEach(track=>track.stop());if(text){if(voiceMode ==="chat"){setInput(text)}else{setInput(current=>(current?`${current} ${text}`.trim():text))}}};media.current=rec;rec.start();setRecording(true);setVoiceStatus("Listening for voice input…");}).catch(()=>setVoiceStatus("Microphone access is blocked"))}
 function startVoiceChat(){if(recording){if(recognitionRef.current) recognitionRef.current.stop();setRecording(false);setVoiceStatus("Ready");return}const SpeechRecognitionCtor=(window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;if(!SpeechRecognitionCtor){setVoiceStatus("Speech recognition is not supported in this browser");return}const recognition=new SpeechRecognitionCtor();recognitionRef.current=recognition;recognition.lang="en-US";recognition.continuous=true;recognition.interimResults=true;recognition.onstart=()=>{setRecording(true);setVoiceStatus("Listening for live Leo chat…")};recognition.onresult=(event:any)=>{let transcript="";for(let i=0;i<event.results.length;i+=1){transcript+=event.results[i][0].transcript}setInput(transcript.trim())};recognition.onerror=()=>{setVoiceStatus("Voice chat is unavailable right now");setRecording(false)};recognition.onend=()=>{setRecording(false);setVoiceStatus("Ready")};recognition.start()}
 const composer=<div className="space-y-3"><div className="flex items-center justify-between gap-2 rounded-2xl border border-white/10 bg-black/40 p-2 text-[11px] uppercase tracking-[0.18em] text-zinc-300"><div className="flex items-center gap-2"><button onClick={()=>setVoiceMode("text")} className={`rounded-full px-2 py-1 ${voiceMode ==="text"?"bg-orange-500 text-black":"text-zinc-300"}`}>Text</button><button onClick={()=>setVoiceMode("input")} className={`rounded-full px-2 py-1 ${voiceMode ==="input"?"bg-orange-500 text-black":"text-zinc-300"}`}><span className="inline-flex items-center gap-1"><Mic size={12}/>Input</span></button><button onClick={()=>setVoiceMode("chat")} className={`rounded-full px-2 py-1 ${voiceMode ==="chat"?"bg-orange-500 text-black":"text-zinc-300"}`}><span className="inline-flex items-center gap-1"><Volume2 size={12}/>Chat</span></button></div><span className="text-[10px] text-orange-300">{voiceStatus}</span></div><div className="flex items-center gap-2 rounded-2xl border border-white/10 bg-black/40 p-2"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} className="min-w-0 flex-1 bg-transparent px-3 py-3 outline-none" placeholder={voiceMode ==="chat"?"Speak or type to Leo...":"Message Leo..."}/><button onClick={generateImage} title="Create image" className="rounded-xl p-3"><ImageIcon size={18}/></button><button onClick={()=>voiceMode ==="chat"?startVoiceChat():startVoiceInput()} title={voiceMode ==="chat"?"Voice chat":"Voice input"} className="rounded-xl p-3">{recording?"●":<Mic size={18}/>}</button><button onClick={()=>send()} className="rounded-xl bg-orange-500 p-3 text-black"><Send size={18}/></button></div></div>;
 const messagesView=<div className="space-y-3">{messages.map((m,i)=><div key={i} className={m.role==='user'?"ml-auto max-w-[88%] rounded-3xl bg-orange-500 p-3 text-black":"max-w-[92%] rounded-3xl border border-white/10 bg-black/40 p-3"}>{m.content}{m.image&&<img src={m.image} alt="Generated by Leo" className="mt-3 max-h-72 rounded-2xl"/>}</div>)}{loading&&<div className="max-w-fit rounded-3xl bg-black/40 p-3 text-zinc-400">Leo is thinking…</div>}</div>;
 if(full)return <div className="h-[calc(100vh-73px)]"><div className="relative mx-auto flex h-full max-w-6xl flex-col overflow-hidden rounded-3xl border border-white/10 bg-white/[.04] backdrop-blur-xl"><header className="relative flex items-center justify-between border-b border-white/10 p-4"><div className="flex items-center gap-3"><div className="relative rounded-xl bg-orange-500 p-2"><span className="absolute inset-0 animate-ping rounded-xl bg-orange-400/50"/><Bot size={20} className="relative"/></div><div><div className="flex items-center gap-2"><b>LEO AI</b>{plan&&<span className="rounded-full border border-orange-400/30 bg-orange-500/10 px-2 py-0.5 text-[10px] uppercase text-orange-300">{plan} active</span>}</div><div className="text-xs text-green-400">● Online</div></div></div><button onClick={()=>setMessages([])} className="flex items-center gap-2 text-sm text-zinc-400"><Trash2 size={16}/>Clear Chat</button></header><div className="flex-1 overflow-y-auto p-4 md:p-8">{messages.length===0&&<div className="mx-auto max-w-2xl py-10 text-center"><div className="mx-auto mb-5 flex h-24 w-24 items-center justify-center rounded-full border border-orange-300/40 bg-orange-500/10"><div className="h-14 w-14 animate-pulse rounded-full bg-orange-400/80 blur-[2px]"/></div><h1 className="text-3xl font-black md:text-5xl">Welcome, {welcomeName} 👋</h1><p className="mt-3 text-zinc-400">What are we building today?</p><div className="mt-7 flex flex-wrap justify-center gap-3">{actions.map(({label,prompt,icon:Icon})=><button key={label} onClick={()=>send(prompt)} className="flex items-center gap-2 rounded-full border border-white/10 bg-black/30 px-4 py-3 text-sm hover:border-orange-400/60"><Icon size={16}/>{label}</button>)}</div></div>}{messagesView}</div><div className="border-t border-white/10 p-3 md:p-5"><div className="mx-auto mb-3 flex max-w-3xl gap-2 overflow-x-auto">{actions.map(({label,prompt,icon:Icon})=><button key={label} onClick={()=>setInput(prompt)} className="flex items-center gap-2 whitespace-nowrap rounded-full border border-white/10 px-4 py-2 text-sm"><Icon size={14}/>{label.replace("Let’s ","")}</button>)}</div><div className="mx-auto max-w-3xl">{composer}</div></div></div></div>;
 return <div className="fixed bottom-4 right-4 z-[60]">{open&&<div className="mb-3 flex h-[min(70vh,620px)] w-[min(92vw,390px)] flex-col overflow-hidden rounded-3xl border border-white/10 bg-zinc-950/95 shadow-2xl backdrop-blur-xl"><header className="flex items-center justify-between border-b border-white/10 p-4"><div className="flex items-center gap-3"><div className="rounded-xl bg-orange-500 p-2"><Bot size={18}/></div><div><b>LEO AI</b><div className="text-xs text-green-400">● Online</div></div></div><div className="flex gap-1"><button onClick={()=>location.href='/app'} className="rounded-lg p-2 text-zinc-400" title="Open full Leo"><Maximize2 size={16}/></button><button onClick={()=>setOpen(false)} className="rounded-lg p-2 text-zinc-400"><X size={16}/></button></div></header><div className="flex-1 overflow-y-auto p-3">{messages.length===0?<div className="py-10 text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-orange-500/10"><Bot/></div><h3 className="mt-4 text-xl font-bold">Hi, I’m Leo 👋</h3><p className="mt-2 text-sm text-zinc-400">Ask me anything or tell me what you want to create.</p><div className="mt-5 grid gap-2">{actions.slice(0,3).map(({label,prompt})=><button key={label} onClick={()=>send(prompt)} className="rounded-xl border border-white/10 px-3 py-2 text-left text-sm">{label}</button>)}</div></div>:messagesView}</div><div className="border-t border-white/10 p-3">{composer}</div></div>}<button onClick={()=>setOpen(v=>!v)} aria-label="Open Leo AI" className="flex h-14 w-14 items-center justify-center rounded-full bg-orange-500 text-black shadow-xl shadow-orange-500/20 hover:scale-105 transition"><Bot/></button></div>;
}
