import {NextRequest,NextResponse} from 'next/server';
import {getUserFromRequest,adminSupabase} from '@/lib/auth';
import {generateSecret,generateURI,verify} from 'otplib';
import QRCode from 'qrcode';
import crypto from 'node:crypto';
const OWNER='leonardudoh5@gmail.com'; const COOKIE='leo_admin_device'; const DAYS=365;
function hash(v:string){return crypto.createHash('sha256').update(v).digest('hex')}
function deviceHash(req:NextRequest){return hash(req.headers.get('user-agent')||'unknown')}
async function trust(db:any,userId:string,req:NextRequest){const raw=crypto.randomBytes(32).toString('hex');await db.from('admin_trusted_devices').insert({user_id:userId,token_hash:hash(raw),user_agent_hash:deviceHash(req),device_label:'Trusted browser',expires_at:new Date(Date.now()+DAYS*86400000).toISOString()});return raw}
export async function POST(req:NextRequest){const user=await getUserFromRequest(req);if(!user||user.email?.toLowerCase()!==OWNER)return NextResponse.json({error:'Forbidden'},{status:403});const db=adminSupabase();const {data:p}=await db.from('profiles').select('*').eq('id',user.id).single();if(!p)return NextResponse.json({error:'Profile not found'},{status:404});const body=await req.json().catch(()=>({}));
 if(body.action==='setup'){if(p.twofa_verified)return NextResponse.json({error:'2FA is already enabled. Use a trusted-device verification when this browser is not recognized.'},{status:409});const secret=generateSecret();await db.from('profiles').update({twofa_secret:secret,twofa_verified:false,admin_locked_until:null}).eq('id',user.id);const uri=generateURI({issuer:'LEO OS',label:user.email,secret});return NextResponse.json({qr:await QRCode.toDataURL(uri),secret});}
 if(body.action==='verify'){if(p.admin_locked_until&&new Date(p.admin_locked_until)>new Date())return NextResponse.json({error:'Admin verification is temporarily locked. Try again later.'},{status:429});if(!p.twofa_secret)return NextResponse.json({error:'Start setup first'},{status:400});const ok=await verify({token:String(body.code),secret:p.twofa_secret});if(!ok){const attempts=Number(p.admin_2fa_failed_attempts||0)+1;const locked=attempts>=3?new Date(Date.now()+15*60*1000).toISOString():null;await db.from('profiles').update({admin_2fa_failed_attempts:locked?0:attempts,admin_locked_until:locked}).eq('id',user.id);await db.from('admin_logs').insert({user_id:user.id,action:locked?'2fa_lockout':'2fa_failed'});return NextResponse.json({error:locked?'Too many failed codes. Admin access is locked for 15 minutes.':'Invalid code'},{status:400});}const codes=Array.from({length:10},()=>crypto.randomBytes(5).toString('hex').toUpperCase());await db.from('profiles').update({twofa_verified:true,backup_codes:codes,admin_2fa_failed_attempts:0,admin_locked_until:null}).eq('id',user.id);const raw=await trust(db,user.id,req);await db.from('admin_logs').insert({user_id:user.id,action:'2fa_verified'});const res=NextResponse.json({ok:true,backup_codes:codes,trusted_for_days:DAYS});res.cookies.set(COOKIE,raw,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:DAYS*86400});return res;}
 if(body.action==='status')return NextResponse.json({verified:!!p.twofa_verified,locked_until:p.admin_locked_until||null});
 return NextResponse.json({error:'Unknown action'},{status:400});}
