'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {createBrowserClient} from '@supabase/ssr';
import {GlassCard} from '@/components/GlassCard';
import {BookOpen,FileUp,Globe,History,Search,Settings2,TestTube2,Archive,Save} from 'lucide-react';

export default function TrainLeo(){
 const router=useRouter();
 const [data,setData]=useState<any>({knowledge:[],versions:[],audit:[],instructions:[],modelConfig:[],toolConfig:[],memory:[],conflicts:[],jobs:[]});
 const [session,setSession]=useState<any>(null); const [q,setQ]=useState(''); const [tab,setTab]=useState('knowledge'); const [busy,setBusy]=useState(false);
 const [form,setForm]=useState({title:'',content:'',category:'general',tags:'',source_type:'manual',source_url:'',confidence:'0.8',reliability:'0.8'});
 const [test,setTest]=useState(''); const [answer,setAnswer]=useState<any>(null); const [url,setUrl]=useState('');
 async function auth(){const s=createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);const {data:{session}}=await s.auth.getSession();if(!session){router.push('/auth');return null}setSession(session);return session}
 async function load(s=session){const ss=s||await auth();if(!ss)return;const r=await fetch(`/api/admin/leo/training/knowledge?q=${encodeURIComponent(q)}`,{headers:{Authorization:`Bearer ${ss.access_token}`}});const base=await r.json();if(r.ok){const headers={Authorization:`Bearer ${ss.access_token}`};const [m,c,jobs]=await Promise.all([fetch('/api/admin/leo/training/memory',{headers}).then(x=>x.json()),fetch('/api/admin/leo/training/conflicts',{headers}).then(x=>x.json()),fetch('/api/admin/leo/training/jobs',{headers}).then(x=>x.json())]);setData({...base,memory:m.memory||[],conflicts:c.conflicts||[],jobs:jobs.jobs||[]});}else if(base.error)alert(base.error)}
 useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[]);
 async function post(path:string,body:any,init:any={}){if(!session)return;setBusy(true);try{const r=await fetch(path,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,...(init.headers||{})},body:init.body??JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j}finally{setBusy(false)}}
 async function add(){const j=await post('/api/admin/leo/training/knowledge',form);if(j?.knowledge){setForm({...form,title:'',content:'',tags:'',source_url:''});await load()}}
 async function archive(id:string){await post('/api/admin/leo/training/knowledge',{id,status:'archived'});await load()}
 async function ingestWeb(){const j=await post('/api/admin/leo/training/web',{url,title:url,category:'web'});if(j.knowledge){setUrl('');await load()}}
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file||!session)return;const fd=new FormData();fd.append('file',file);const r=await fetch('/api/admin/leo/training/documents',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`},body:fd});const j=await r.json();if(!r.ok)alert(j.error);else{alert(`Imported ${j.inserted} knowledge item(s).`);await load()}}
 async function runTest(){try{const j=await post('/api/admin/leo/training/test',{message:test});setAnswer(j)}catch(error){setAnswer({reply:error instanceof Error?error.message:'Leo test failed.',sources:[]})}}
 return <main className='mx-auto max-w-7xl px-4 py-10'>
  <div className='flex flex-wrap items-end justify-between gap-4'><div><p className='text-sm font-bold text-orange-300'>OWNER CONTROL CENTER</p><h1 className='mt-2 text-4xl font-black'>Train Leo</h1><p className='mt-2 max-w-3xl text-zinc-400'>Persistent knowledge and instructions are stored separately from the base model. Archive and version changes instead of deleting useful history.</p></div><a href='/admin' className='rounded-full border border-white/10 px-4 py-2 text-sm'>← Admin</a></div>
  <div className='mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-5'>{[
   ['knowledge','Knowledge',BookOpen],['ingest','Ingest',FileUp],['web','Web Knowledge',Globe],['test','Testing Lab',TestTube2],['memory','Memory',BookOpen],['history','History',History],['conflicts','Conflicts',Search],['jobs','Jobs',Settings2],['config','Config',Settings2]
  ].map(([id,label,Icon]:any)=><button key={id} onClick={()=>setTab(id)} className={`rounded-2xl border p-4 text-left ${tab===id?'border-orange-400 bg-orange-500/10':'border-white/10 bg-white/[.03]'}`}><Icon size={18}/><b className='mt-2 block'>{label}</b></button>)}</div>
  {tab==='knowledge'&&<section className='mt-6 grid gap-6 lg:grid-cols-[1fr_1.2fr]'><GlassCard className='p-6'><h2 className='text-xl font-bold'>Add knowledge</h2><div className='mt-4 grid gap-3'>{[['title','Title'],['category','Category'],['tags','Tags (comma separated)'],['source_url','Source URL']].map(([k,l])=><input key={k} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={l} className='rounded-xl border border-white/10 bg-black/40 p-3'/>)}<textarea value={form.content} onChange={e=>setForm({...form,content:e.target.value})} placeholder='Knowledge content' className='min-h-48 rounded-xl border border-white/10 bg-black/40 p-3'/><button disabled={busy} onClick={add} className='rounded-xl bg-orange-500 p-3 font-bold'><Save size={16} className='mr-2 inline'/>Save knowledge</button></div></GlassCard><GlassCard className='p-6'><div className='flex gap-2'><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder='Search knowledge...' className='min-w-0 flex-1 rounded-xl border border-white/10 bg-black/40 p-3'/><button onClick={()=>load()} className='rounded-xl border border-white/10 p-3'><Search size={18}/></button></div><div className='mt-5 space-y-3'>{data.knowledge.map((x:any)=><div key={x.id} className='rounded-2xl border border-white/10 p-4'><div className='flex justify-between gap-3'><div><b>{x.title}</b><div className='mt-1 text-xs text-zinc-500'>{x.category} • {x.source_type} • v{x.version}</div></div>{x.status==='active'&&<button onClick={()=>archive(x.id)} className='text-xs text-orange-300'><Archive size={14} className='inline mr-1'/>Archive</button>}</div><p className='mt-3 line-clamp-4 text-sm text-zinc-300'>{x.content}</p></div>)}</div></GlassCard></section>}
  {tab==='ingest'&&<section className='mt-6 grid gap-6 md:grid-cols-2'><GlassCard className='p-6'><h2 className='text-xl font-bold'>Upload documents</h2><p className='mt-2 text-sm text-zinc-400'>PDF, TXT, Markdown, JSON, code files and ZIP archives can be ingested into persistent knowledge.</p><label className='mt-6 block rounded-2xl border border-dashed border-white/20 p-8 text-center cursor-pointer'><FileUp className='mx-auto'/><span className='mt-2 block'>Choose a file</span><input type='file' className='hidden' onChange={upload}/></label></GlassCard><GlassCard className='p-6'><h2 className='text-xl font-bold'>Knowledge model</h2><p className='mt-3 text-zinc-400'>Leo retrieves relevant stored knowledge at chat time. Updating knowledge does not require retraining the underlying model.</p><ul className='mt-5 space-y-2 text-sm'><li>✓ Version history</li><li>✓ Confidence and reliability</li><li>✓ Source metadata</li><li>✓ Archive instead of destructive delete</li></ul></GlassCard></section>}
  {tab==='web'&&<section className='mt-6 grid gap-6 md:grid-cols-2'><GlassCard className='p-6'><h2 className='text-xl font-bold'>Ingest a web source</h2><p className='mt-2 text-sm text-zinc-400'>Use a real source URL. The fetched text is stored with its URL so you can review or archive it later.</p><input value={url} onChange={e=>setUrl(e.target.value)} placeholder='https://example.com/source' className='mt-5 w-full rounded-xl border border-white/10 bg-black/40 p-3'/><button disabled={busy} onClick={ingestWeb} className='mt-3 rounded-xl bg-orange-500 px-5 py-3 font-bold'><Globe className='mr-2 inline' size={16}/>Import source</button></GlassCard><GlassCard className='p-6'><h2 className='text-xl font-bold'>Source priority</h2><ol className='mt-4 space-y-2 text-sm text-zinc-300'><li>1. System and safety instructions</li><li>2. Verified live tools</li><li>3. Verified external sources</li><li>4. Persistent Leo knowledge</li><li>5. Client/project knowledge</li><li>6. General model knowledge</li><li>7. Unverified information</li></ol></GlassCard></section>}
  {tab==='test'&&<section className='mt-6 grid gap-6 lg:grid-cols-2'><GlassCard className='p-6'><h2 className='text-xl font-bold'>Leo Testing Lab</h2><textarea value={test} onChange={e=>setTest(e.target.value)} placeholder='Ask Leo something that should use stored knowledge...' className='mt-4 min-h-40 w-full rounded-xl border border-white/10 bg-black/40 p-3'/><button disabled={busy} onClick={runTest} className='mt-3 rounded-xl bg-orange-500 px-5 py-3 font-bold'>Run test</button></GlassCard><GlassCard className='p-6'><h2 className='text-xl font-bold'>Result</h2><p className='mt-4 whitespace-pre-wrap text-zinc-300'>{answer?.reply||'No test run yet.'}</p>{answer?.sources?.length>0&&<div className='mt-6 border-t border-white/10 pt-4'><b>Retrieved sources</b>{answer.sources.map((s:any)=><div key={s.id} className='mt-2 text-sm text-zinc-400'>• {s.title} — {s.category}</div>)}</div>}</GlassCard></section>}
  {tab==='memory'&&<section className='mt-6'><GlassCard className='p-6'><h2 className='text-xl font-bold'>Persistent user memory</h2><p className='mt-2 text-sm text-zinc-400'>Memory is separate from Leo knowledge and can be reviewed or changed without retraining the model.</p><div className='mt-5 space-y-3'>{data.memory.map((m:any)=><div key={m.id} className='rounded-xl border border-white/10 p-4'><b>{m.memory_key}</b><p className='mt-1 text-sm text-zinc-300'>{m.memory_value}</p></div>)}</div></GlassCard></section>}
  {tab==='history'&&<section className='mt-6 grid gap-6 lg:grid-cols-2'><GlassCard className='p-6'><h2 className='text-xl font-bold'>Version history</h2><div className='mt-4 space-y-3'>{data.versions.map((v:any)=><div key={v.id} className='rounded-xl border border-white/10 p-4'><b>v{v.version}</b><span className='ml-2 text-xs text-zinc-500'>{v.change_type}</span><div className='mt-1 text-xs text-zinc-500'>{new Date(v.created_at).toLocaleString()}</div></div>)}</div></GlassCard><GlassCard className='p-6'><h2 className='text-xl font-bold'>Audit history</h2><div className='mt-4 max-h-96 space-y-3 overflow-auto'>{data.audit.map((a:any)=><div key={a.id} className='rounded-xl border border-white/10 p-3 text-sm'><b>{a.action}</b><div className='text-xs text-zinc-500'>{new Date(a.created_at).toLocaleString()}</div></div>)}</div></GlassCard></section>}
  {tab==='conflicts'&&<section className='mt-6'><GlassCard className='p-6'><h2 className='text-xl font-bold'>Potential knowledge conflicts</h2><p className='mt-2 text-sm text-zinc-400'>Leo flags duplicate title/category records for review instead of silently choosing between them.</p><div className='mt-4 space-y-4'>{data.conflicts.map((c:any)=><div key={c.key} className='rounded-xl border border-orange-400/30 p-4'><b>{c.key}</b>{c.items.map((x:any)=><div key={x.id} className='mt-2 text-sm text-zinc-300'>{x.source_type} • confidence {x.confidence} • {x.content.slice(0,240)}…</div>)}</div>)}</div></GlassCard></section>}
  {tab==='jobs'&&<section className='mt-6'><GlassCard className='p-6'><h2 className='text-xl font-bold'>Training jobs</h2><div className='mt-4 space-y-3'>{data.jobs.map((j:any)=><div key={j.id} className='rounded-xl border border-white/10 p-4'><b>{j.job_type}</b><span className='ml-2 text-xs text-zinc-500'>{j.status}</span><div className='mt-1 text-xs text-zinc-500'>{new Date(j.created_at).toLocaleString()}</div></div>)}</div></GlassCard></section>}
  {tab==='config'&&<section className='mt-6 grid gap-6 lg:grid-cols-2'><GlassCard className='p-6'><h2 className='text-xl font-bold'>System instructions</h2><p className='mt-2 text-sm text-zinc-400'>Add high-priority behavior without changing the base model.</p><InstructionForm session={session} onSaved={()=>load()}/></GlassCard><GlassCard className='p-6'><h2 className='text-xl font-bold'>Model & tools</h2><div className='mt-4 space-y-2 text-sm text-zinc-400'>{data.modelConfig.map((x:any)=><div key={x.key}>{x.key}: <b>{x.value}</b></div>)}{data.toolConfig.map((x:any)=><div key={x.tool_name}>{x.tool_name}: <b>{x.enabled?'enabled':'disabled'}</b></div>)}</div></GlassCard></section>}
  <div className='mt-8 text-xs text-zinc-600'><History size={14} className='mr-1 inline'/>Training changes are auditable and versioned.</div>
 </main>
}
function InstructionForm({session,onSaved}:{session:any;onSaved:()=>void}){const [name,setName]=useState('Leo behavior');const [content,setContent]=useState('');const [busy,setBusy]=useState(false);async function save(){setBusy(true);try{const r=await fetch('/api/admin/leo/training/config',{method:'POST',headers:{Authorization:`Bearer ${session?.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({kind:'instruction',name,content,priority:50})});if(!r.ok)alert((await r.json()).error);else{setContent('');onSaved()}}finally{setBusy(false)}}return <div className='mt-4 space-y-3'><input value={name} onChange={e=>setName(e.target.value)} className='w-full rounded-xl border border-white/10 bg-black/40 p-3' placeholder='Instruction name'/><textarea value={content} onChange={e=>setContent(e.target.value)} className='min-h-36 w-full rounded-xl border border-white/10 bg-black/40 p-3' placeholder='Example: When explaining coding, provide a clear step-by-step solution.'/><button disabled={busy||!content.trim()} onClick={save} className='rounded-xl bg-orange-500 px-5 py-3 font-bold'>Save instruction</button></div>}
