'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {createBrowserClient} from '@supabase/ssr';
import {useRouter} from 'next/navigation';

export default function AgentsAdmin(){
 const router=useRouter();
 const [agents,setAgents]=useState<any[]>([]),[runs,setRuns]=useState<any[]>([]),[task,setTask]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[session,setSession]=useState<any>(null);
 const load=useCallback(async()=>{const s=createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);const {data:{session:auth}}=await s.auth.getSession();if(!auth){router.replace('/auth');return}const r=await fetch('/api/agents',{headers:{Authorization:`Bearer ${auth.access_token}`},cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Agents could not be loaded.');setAgents(j.agents||[]);const q=await fetch('/api/admin/agents',{headers:{Authorization:`Bearer ${auth.access_token}`},cache:'no-store'});if(q.ok){const x=await q.json();setRuns(x.runs||[]) }},[router]);
 useEffect(()=>{const timer=window.setTimeout(()=>{void load().catch(error=>setMessage(error instanceof Error?error.message:'Agents could not be loaded.'))},0);return()=>window.clearTimeout(timer)},[load]);
 const runVideo=async()=>{if(!task.trim())return;setBusy(true);setMessage('Starting Leo Video Agent…');try{const r=await fetch('/api/agents/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({agent_id:'video',task:task.trim()})});const j=await r.json();if(j.approval_id){const a=confirm('Video generation can consume Runway credits. Approve this generation?');if(!a){setMessage('Cancelled.');return}const ar=await fetch('/api/agents/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approval_id:j.approval_id})});const aj=await ar.json();setMessage(aj.message||aj.status||aj.error||'Done');let vr:any=null;try{vr=aj.result?JSON.parse(aj.result):null}catch{};if(vr?.task_id&&aj.agent?.id==='video'){setMessage('Runway is generating the video…');for(let i=0;i<90;i++){await new Promise(r=>setTimeout(r,5000));const sr=await fetch('/api/agents/video',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task_id:vr.task_id,run_id:j.run_id})});const sj=await sr.json();if(sj.status==='completed'){setMessage('Video is ready.');if(sj.video_url)window.open(sj.video_url,'_blank');break}if(sj.status==='failed'){setMessage(sj.error||'Video generation failed.');break}}}}else{setMessage(j.message||j.status||j.error||'Done')}await load()}catch(e){setMessage(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}};
 const runBrowser=async()=>{if(!task.trim())return;setBusy(true);setMessage('Starting Leo browser agent…');try{const r=await fetch('/api/agents/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({agent_id:'browser',task:task.trim()})});const j=await r.json();if(j.approval_id){const a=confirm('This owner-only browser agent requires approval. Start it now?');if(!a){setMessage('Cancelled.');return}const ar=await fetch('/api/agents/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approval_id:j.approval_id})});const aj=await ar.json();setMessage(aj.message||aj.status||aj.error||'Done');if(aj.session_id)setSession(aj);else if(aj.status==='completed')setTask('')}else{setMessage(j.message||j.status||j.error||'Done');if(j.session_id)setSession(j);else if(j.status==='completed')setTask('')}await load()}catch(e){setMessage(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}};
 const approveBrowser=async(decision:'approve'|'deny'|'cancel')=>{if(!session?.session_id||!session?.approvals?.[0])return;const p=session.approvals[0];setBusy(true);try{const r=await fetch('/api/agents/browser',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'approve',run_id:session.run_id,session_id:session.session_id,approval:{request_id:p.request_id,type:p.type,decision}})});const j=await r.json();setMessage(j.message||j.status||j.error||'Approval sent');if(decision!=='approve'){setSession(null);return}const c=await fetch('/api/agents/browser',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'continue',run_id:session.run_id,session_id:session.session_id})});const cj=await c.json();setMessage(cj.result||cj.message||cj.status||cj.error||'Browser agent updated');setSession(cj.status==='waiting_owner_input'?cj:null);await load()}finally{setBusy(false)}};
 return <main className='mx-auto max-w-7xl px-4 py-8'><div className='mb-6 flex items-center justify-between'><div><Link href='/admin' className='text-sm text-zinc-500'>← Admin</Link><h1 className='mt-2 text-4xl font-black'>Owner Agents</h1><p className='mt-2 text-zinc-400'>Server-authorized specialist capabilities and real execution history.</p></div></div>
 <section className='mb-10 rounded-2xl border border-orange-400/20 bg-orange-400/[.04] p-5'><h2 className='text-xl font-bold'>Leo Browser / Computer Console</h2><p className='mt-1 text-sm text-zinc-400'>Owner-only. Leo can navigate pages and interact with browser interfaces through OpenAI-hosted computer use. Consequential actions still require owner approval.</p><textarea value={task} onChange={e=>setTask(e.target.value)} placeholder='Example: Open my website and inspect the homepage navigation.' className='mt-4 min-h-28 w-full rounded-xl border border-white/10 bg-black/20 p-3 outline-none'/><button disabled={busy} onClick={runBrowser} className='mt-3 rounded-xl bg-orange-400 px-4 py-2 font-bold text-black disabled:opacity-50'>{busy?'Working…':'Run Browser Agent'}</button><button disabled={busy} onClick={runVideo} className='ml-2 mt-3 rounded-xl border border-orange-400/40 px-4 py-2 font-bold text-orange-300 disabled:opacity-50'>{busy?'Working…':'Run Video Agent'}</button>{message&&<p className='mt-3 text-sm text-zinc-300'>{message}</p>}{session?.approvals?.[0]&&<div className='mt-4 rounded-xl border border-yellow-400/20 bg-yellow-400/[.04] p-4'><p className='font-semibold'>Owner input required</p><p className='mt-1 text-sm text-zinc-400'>{session.approvals[0].reason||session.approvals[0].origin||'The browser is requesting permission.'}</p><div className='mt-3 flex gap-2'><button onClick={()=>approveBrowser('approve')} className='rounded-lg bg-emerald-400 px-3 py-2 text-sm font-bold text-black'>Approve</button><button onClick={()=>approveBrowser('deny')} className='rounded-lg border border-white/10 px-3 py-2 text-sm'>Deny</button><button onClick={()=>approveBrowser('cancel')} className='rounded-lg border border-white/10 px-3 py-2 text-sm'>Cancel</button></div></div>}</section>
 <div className='grid gap-4 sm:grid-cols-2 lg:grid-cols-3'>{agents.map(a=><div key={a.id} className='rounded-2xl border border-white/10 bg-white/[.03] p-5'><div className='flex items-start justify-between gap-3'><div><h2 className='font-bold'>{a.name}</h2><p className='mt-1 text-sm text-zinc-400'>{a.description}</p></div><span className='rounded-full border border-orange-400/30 px-2 py-1 text-[10px] uppercase text-orange-300'>{a.category}</span></div><div className='mt-4 flex flex-wrap gap-2'>{a.permissions.map((p:string)=><span key={p} className='rounded-lg bg-white/5 px-2 py-1 text-xs'>{p}</span>)}</div>{a.approvalRequired&&<p className='mt-3 text-xs text-yellow-300'>Approval required</p>}</div>)}</div><section className='mt-10 rounded-2xl border border-white/10 p-5'><h2 className='text-xl font-bold'>Recent Agent Runs</h2><div className='mt-4 overflow-auto'><table className='w-full text-left text-sm'><thead><tr className='border-b border-white/10'><th className='p-3'>Agent</th><th className='p-3'>Task</th><th className='p-3'>Status</th><th className='p-3'>Time</th></tr></thead><tbody>{runs.map(r=><tr key={r.id} className='border-b border-white/5'><td className='p-3'>{r.agent_id}</td><td className='max-w-md p-3 truncate'>{r.task}</td><td className='p-3'>{r.status}</td><td className='p-3'>{new Date(r.created_at).toLocaleString()}</td></tr>)}</tbody></table>{!runs.length&&<p className='py-8 text-center text-zinc-500'>No agent runs yet.</p>}</div></section></main>
}
