"use client";
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { createBrowserClient } from '@supabase/ssr';
import { Activity, ArrowRight, Bell, Bot, ChevronRight, FolderKanban, Globe2, LayoutDashboard, LogOut, Menu, MessageSquare , Settings, Sparkles, X, Zap } from 'lucide-react';

type Data = { user:{name:string;email:string}; owner:boolean; plan:string; status:string; billingPeriod:string|null; endsAt:string|null; credits:number|string; counts:{conversations:number;memories:number;projects:number;websites:number;unreadNotifications:number}; conversations:{id:string;title:string|null;updated_at:string}[]; projects:{id:string;project_name:string;type:string|null;status:string|null;progress:number|null;created_at:string}[]; websites:{id:string;business_name:string|null;website_type:string;status:string;live_url:string|null;updated_at:string}[]; notifications:{id:string;title:string;body:string;created_at:string;read:boolean}[]; activity:{id:string;kind:string;title:string;created_at:string}[]; usageTrend:{date:string;tokens:number}[] };
const nav=[['Overview','/dashboard',LayoutDashboard],['Leo','/app',Bot],['Projects','/templates',FolderKanban],['Websites','/setup',Globe2],['Activity','#activity',Activity],['Usage','#usage',Zap],['Settings','/account',Settings]] as const;
function Card({children,className='',id }:{children:React.ReactNode;className?:string;id?:string}){return <section id={id} className={`rounded-3xl border border-white/[.08] bg-white/[.035] p-5 shadow-[0_20px_70px_rgba(0,0,0,.18)] backdrop-blur-xl ${className}`}>{children}</section>}
function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'L'}
function ago(date:string){const s=Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/1000));if(s<60)return 'just now';if(s<3600)return `${Math.floor(s/60)}m ago`;if(s<86400)return `${Math.floor(s/3600)}h ago`;return `${Math.floor(s/86400)}d ago`}
function UsageChart({values}:{values:{date:string;tokens:number}[]}){const max=Math.max(...values.map(v=>v.tokens),1);return <div className="mt-5 flex h-36 items-end gap-2">{values.map(v=><div key={v.date} className="group flex h-full flex-1 flex-col justify-end"><div title={`${v.tokens.toLocaleString()} tokens`} style={{height:`${Math.max(5,(v.tokens/max)*100)}%`}} className="rounded-t-xl bg-[var(--gold)]/80 transition-all group-hover:bg-[var(--gold)]"/><span className="mt-2 text-center text-[10px] text-zinc-600">{new Date(v.date+'T00:00:00').toLocaleDateString(undefined,{weekday:'short'}).slice(0,2)}</span></div>)}</div>}
export default function Dashboard(){
 const [data,setData]=useState<Data|null>(null); const [error,setError]=useState(''); const [drawer,setDrawer]=useState(false);
 useEffect(()=>{let alive=true;(async()=>{const s=createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);const session=(await s.auth.getSession()).data.session;if(!session){location.assign('/auth');return}const r=await fetch('/api/dashboard',{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Dashboard could not be loaded.');if(alive)setData(d)})().catch(e=>alive&&setError(e.message));return()=>{alive=false}},[]);
 const greeting=useMemo(()=>{const h=new Date().getHours();return h<12?'Good morning':h<18?'Good afternoon':'Good evening'},[]);
 if(error)return <main className="mx-auto max-w-7xl px-4 py-12"><Card><p role="alert" className="text-red-200">{error}</p></Card></main>;
 if(!data)return <main className="mx-auto max-w-7xl px-4 py-12"><div className="h-10 w-64 animate-pulse rounded-xl bg-white/10"/><div className="mt-8 grid gap-4 md:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-32 animate-pulse rounded-3xl bg-white/5"/>)}</div></main>;
 const metric=[['AI conversations',data.counts.conversations,MessageSquare],['Credits',data.credits,Zap],['Projects',data.counts.projects,FolderKanban],['Websites',data.counts.websites,Globe2]] as const;
 return <main className="min-h-[calc(100vh-64px)]"><div className="mx-auto flex max-w-[1600px] gap-4 px-3 py-3 sm:px-5 lg:px-6">
  <aside className={`fixed inset-y-[65px] left-0 z-50 w-72 transform border-r border-white/10 bg-[#090909]/95 p-4 backdrop-blur-2xl transition-transform lg:sticky lg:top-[76px] lg:z-20 lg:h-[calc(100vh-88px)] lg:translate-x-0 lg:rounded-3xl lg:border ${drawer?'translate-x-0':'-translate-x-full'}`}>
   <div className="flex items-center justify-between px-2 py-2 lg:hidden"><b>LEO OS</b><button onClick={()=>setDrawer(false)} aria-label="Close sidebar"><X/></button></div>
   <div className="mb-7 hidden items-center gap-3 px-2 lg:flex"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[var(--gold)] font-black text-black">L</div><div><b className="tracking-tight">LEO OS</b><p className="text-[11px] text-zinc-500">AI workspace</p></div></div>
   <nav className="space-y-1">{nav.map(([label,href,Icon])=><Link onClick={()=>setDrawer(false)} key={label} href={href} className={`flex items-center gap-3 rounded-2xl px-3 py-3 text-sm ${label==='Overview'?'bg-white/[.08] text-white':'text-zinc-400 hover:bg-white/[.05] hover:text-white'}`}><Icon size={18}/><span>{label}</span>{label==='Overview'&&<ChevronRight size={15} className="ml-auto text-zinc-600"/>}</Link>)}</nav>
   <div className="mt-auto hidden lg:block"><div className="my-5 h-px bg-white/10"/><div className="flex items-center gap-3 rounded-2xl bg-white/[.04] p-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-white/10 text-xs font-bold">{initials(data.user.name)}</div><div className="min-w-0"><p className="truncate text-sm font-semibold">{data.user.name}</p><p className="truncate text-xs text-zinc-500">{data.plan}</p></div></div><Link href="/api/auth/logout" className="mt-2 flex items-center gap-2 px-3 py-2 text-xs text-zinc-500 hover:text-white"><LogOut size={14}/> Logout</Link></div>
  </aside>
  {drawer&&<button aria-label="Close sidebar" className="fixed inset-0 z-40 bg-black/60 lg:hidden" onClick={()=>setDrawer(false)}/>} 
  <div className="min-w-0 flex-1 py-1 sm:py-3">
   <div className="mb-5 flex items-center justify-between gap-3"><button className="rounded-xl border border-white/10 p-2 lg:hidden" onClick={()=>setDrawer(true)} aria-label="Open dashboard navigation"><Menu size={20}/></button><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--gold)]">LEO OS WORKSPACE</p><h1 className="mt-1 truncate text-2xl font-black sm:text-3xl">{data.owner?'Welcome back, Boss Leonard 👑':`${greeting}, ${data.user.name}`}</h1><p className="mt-1 hidden text-sm text-zinc-500 sm:block">Your AI workspace is ready.</p></div><div className="flex items-center gap-2"><Link href="/notifications" className="relative rounded-xl border border-white/10 p-2.5" aria-label="Notifications"><Bell size={18}/>{data.counts.unreadNotifications>0&&<span className="absolute right-1 top-1 h-2 w-2 rounded-full bg-[var(--gold)]"/>}</Link><Link href="/app" className="hidden rounded-xl bg-[var(--gold)] px-4 py-2.5 text-sm font-bold text-black sm:inline-flex"><Bot size={16} className="mr-2"/> Ask Leo</Link></div></div>
   <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metric.map(([label,value,Icon])=><Card key={label} className="relative overflow-hidden"><div className="flex items-center justify-between"><span className="text-sm text-zinc-500">{label}</span><Icon size={18} className="text-[var(--gold)]"/></div><p className="mt-5 text-3xl font-black">{typeof value==='number'?value.toLocaleString():value}</p><p className="mt-1 text-xs text-zinc-600">Live account data</p></Card>)}</div>
   <div className="mt-3 grid gap-3 xl:grid-cols-[1.35fr_.65fr]" id="usage"><Card><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold">AI usage</p><p className="mt-1 text-xs text-zinc-500">Real token activity from the last 7 days</p></div><span className="rounded-full border border-white/10 px-2.5 py-1 text-[11px] text-zinc-400">{data.plan}</span></div><UsageChart values={data.usageTrend}/></Card><Card><p className="text-sm font-semibold">Workspace access</p><p className="mt-5 text-2xl font-black">{data.plan}</p><p className="mt-1 text-sm text-zinc-500">{data.status==='owner'?'Owner access':'Current account plan'}</p><div className="mt-6 flex items-center justify-between border-t border-white/10 pt-4 text-sm"><span className="text-zinc-500">Renewal</span><span>{data.endsAt?new Date(data.endsAt).toLocaleDateString():'—'}</span></div><Link href="/pricing" className="mt-5 inline-flex items-center text-sm font-semibold text-[var(--gold)]">Manage plan <ArrowRight size={15} className="ml-1"/></Link></Card></div>
  <div className="mt-3 grid gap-3 xl:grid-cols-[1fr_1fr]"><Card><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Projects</p><p className="mt-1 text-xs text-zinc-500">Your latest work</p></div><Link href="/templates" className="text-xs text-[var(--gold)]">View all</Link></div>{data.projects.length?<div className="mt-4 space-y-2">{data.projects.map(p=><Link href="/templates" key={p.id} className="flex items-center gap-3 rounded-2xl border border-white/[.07] p-3 hover:bg-white/[.04]"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-white/[.06]"><FolderKanban size={16}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{p.project_name}</p><p className="text-xs text-zinc-600">{p.type||'Project'} · {p.status||'draft'}</p></div><span className="text-xs text-zinc-600">{ago(p.created_at)}</span></Link>)}</div>:<div className="mt-5 rounded-2xl border border-dashed border-white/10 p-6 text-center"><p className="text-sm text-zinc-400">You haven't created a project yet.</p><Link href="/templates" className="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-[var(--gold)]">Create your first project <ArrowRight size={14}/></Link></div>}</Card>
   <Card><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Websites</p><p className="mt-1 text-xs text-zinc-500">Build and deployment workspace</p></div><Link href="/setup" className="text-xs text-[var(--gold)]">Create</Link></div>{data.websites.length?<div className="mt-4 space-y-2">{data.websites.map(w=><div key={w.id} className="flex items-center gap-3 rounded-2xl border border-white/[.07] p-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-white/[.06]"><Globe2 size={16}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{w.business_name||w.website_type}</p><p className="text-xs text-zinc-600">{w.website_type} · {w.status}</p></div>{w.live_url?<a href={w.live_url} target="_blank" rel="noreferrer" className="text-xs font-semibold text-[var(--gold)]">Open</a>:<span className="text-xs text-zinc-600">Not live</span>}</div>)}</div>:<div className="mt-5 rounded-2xl border border-dashed border-white/10 p-6 text-center"><p className="text-sm text-zinc-400">No website projects yet.</p><Link href="/setup" className="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-[var(--gold)]">Create a website <ArrowRight size={14}/></Link></div>}</Card></div>
   <Card className="mt-3" id="activity"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Recent activity</p><p className="mt-1 text-xs text-zinc-500">Events recorded by LEO OS</p></div><Link href="/notifications" className="text-xs text-[var(--gold)]">Notifications</Link></div>{data.activity.length?<div className="mt-4 divide-y divide-white/[.07]">{data.activity.map(a=><div key={a.id} className="flex items-center gap-3 py-3"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-white/[.05]"><Activity size={14} className="text-zinc-400"/></div><p className="min-w-0 flex-1 truncate text-sm">{a.title}</p><time className="shrink-0 text-xs text-zinc-600">{ago(a.created_at)}</time></div>)}</div>:<div className="mt-5 rounded-2xl border border-dashed border-white/10 p-6 text-center text-sm text-zinc-500">No activity yet.</div>}</Card>
  <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[['Ask Leo','/app',Bot],['Create Website','/setup',Globe2],['Choose Project Template','/templates',FolderKanban]].map(([label,href,Icon])=><Link key={label as string} href={href as string} className="group flex items-center gap-3 rounded-2xl border border-white/[.08] bg-white/[.025] p-4 hover:bg-white/[.05]"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[var(--gold)]/10 text-[var(--gold)]"><Icon size={18}/></span><span className="flex-1 text-sm font-semibold">{label as string}</span><ArrowRight size={15} className="text-zinc-600 transition-transform group-hover:translate-x-1"/></Link>)}</div>
  </div></div></main>
}
